// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWCWwJBP8Ee18Tr8HkVzg_n45gHc2pZbc',
    appId: '1:725859545069:web:754f515d2bd0b5f54881e4',
    messagingSenderId: '725859545069',
    projectId: 'redonto-951d8',
    authDomain: 'redonto-951d8.firebaseapp.com',
    databaseURL: 'https://redonto-951d8-default-rtdb.firebaseio.com',
    storageBucket: 'redonto-951d8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL9_l_GVsNm8cIQu7a2YVVCXI0wmXXabE',
    appId: '1:725859545069:android:ac4164b51d994b614881e4',
    messagingSenderId: '725859545069',
    projectId: 'redonto-951d8',
    databaseURL: 'https://redonto-951d8-default-rtdb.firebaseio.com',
    storageBucket: 'redonto-951d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCazSO4jThj1f2Tl4PUqIBJDiCphBlvbKM',
    appId: '1:725859545069:ios:b2e5ae94a41998474881e4',
    messagingSenderId: '725859545069',
    projectId: 'redonto-951d8',
    databaseURL: 'https://redonto-951d8-default-rtdb.firebaseio.com',
    storageBucket: 'redonto-951d8.appspot.com',
    androidClientId: '725859545069-0vbacqjopn4flcm6vb66do41g8aui7fd.apps.googleusercontent.com',
    iosClientId: '725859545069-cbja24pj2ft7vv4jhude5b8e6qet7jmn.apps.googleusercontent.com',
    iosBundleId: 'com.example.redontoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCazSO4jThj1f2Tl4PUqIBJDiCphBlvbKM',
    appId: '1:725859545069:ios:52fb2d19c758a1684881e4',
    messagingSenderId: '725859545069',
    projectId: 'redonto-951d8',
    databaseURL: 'https://redonto-951d8-default-rtdb.firebaseio.com',
    storageBucket: 'redonto-951d8.appspot.com',
    androidClientId: '725859545069-0vbacqjopn4flcm6vb66do41g8aui7fd.apps.googleusercontent.com',
    iosClientId: '725859545069-m9ksa53rpi95gbrd98e828npfusqdn61.apps.googleusercontent.com',
    iosBundleId: 'com.example.redontoapp.RunnerTests',
  );
}
